baseurl: https://example.com
title: Tyyppiarvo
canonifyurls: yes
languagecode: fi
theme: hugo-tanka
enableEmoji: yes
hasCJKLanguage: no
pygmentsstyle: vs
pygmentscodefences: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  faviconfile: images/favicon.png
  highlightjs: yes
  highlightjslanguages:
    - r
    - python
    - stan
  progressively: no
  sitename: Tyyppiarvon arkisto
  uselatex: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  primary:
    - name: Etusivu
      url: /
      weight: 1
    - name: Tyyppiarvo
      url: /about/
      weight: 2
    - name: Lehtiarkisto
      url: /archive/
      weight: 3
    - name: GitHub
      url: https://github.com/joniok/tyyppiarvo
      weight: 5
